### ISSUE TITLE
error occurred  when I changed the graph(public datasets)! please help me 

### ISSUE THREAD

**Issue by BinGnadenlos** [mengsig/DomiRank#2]
Traceback (most recent call last):
  File "...../multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "......./process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "....../DomiRank-main/domirank.py", line 223, in process_iteration
    ourTempAttack, __ = network_attack_sampled(spArray, domiAttack, sampling = sampling)
  File "......./DomiRank-main/domirank.py", line 125, in network_attack_sampled
    componentEvolution[j] = get_component_size(GAdj)/initialComponent
IndexError: index 100 is out of bounds for axis 0 with size 100

and this is another  situation:

Traceback (most recent call last):
  File "...../multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "......./multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "......./DomiRank-main/domirank.py", line 223, in process_iteration
    ourTempAttack, __ = network_attack_sampled(spArray, domiAttack, sampling = sampling)
  File "......../DomiRank-main/domirank.py", line 114, in network_attack_sampled
    componentEvolution = np.zeros(int(N/sampling))
ZeroDivisionError: division by zero

**Comment by mengsig** [comment]
Hello @BinGnadenlos ,

I would be happy to help. Could you send the network you are using to marcus.w.engsig@gmail.com? 

If the data is proprietary, let me know and I will try and fix it based on these errors, but it will mean I can't troubleshoot. 

Thank you in advance!

Best,
Marcus

**Comment by mengsig** [comment]
However from looking at it, it seems that there is an issue with the sampling which is propagating. 

What is the size of the network @BinGnadenlos ? You can try to set the sampling to 1 or 2 and see if that fixes the issue! 

Best,
Marcus

**Comment by mengsig** [comment]
Hi again @BinGnadenlos ,

I have found the error. Small oversight on my part. Your network is smaller than 100 nodes correct? 

In this case, the algorithm will break. But I will fix it momentarily!

**Comment by mengsig** [comment]
Hello @BinGnadenlos,

The issue should now be fixed.

If it is, let me know so I can close this issue!

Thank you for bringing this to my attention. 

Best,
Marcus

**Comment by chenshuai17** [comment]
Dear Marcus,

Thanks for you excellent work.
I still have the same problem, the dataset I used is the crime network downloaded from the following link: https://github.com/renxiaolong/Generalized-Network-Dismantling/tree/master/Datasets_Main_Paper
Can you tell me how to solve this problem, I would appreciate it.

```
Process Process-94:
Traceback (most recent call last):
  File "/home/chenx/anaconda3/envs/domirank/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/chenx/anaconda3/envs/domirank/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chenx/DomiRank/domirank.py", line 225, in process_iteration
    ourTempAttack, __ = network_attack_sampled(spArray, domiAttack, sampling = sampling)
  File "/home/chenx/DomiRank/domirank.py", line 127, in network_attack_sampled
    componentEvolution[j] = get_component_size(GAdj)/initialComponent
IndexError: index 107 is out of bounds for axis 0 with size 107
Traceback (most recent call last):
  File "/home/chenx/DomiRank/main.py", line 51, in <module>
    sigma, sigmaArray = dr.optimal_sigma(GAdj, analytical = analytical, endVal = lambN) #get the optimal sigma using the space (0, -1/lambN) as computed previously
  File "/home/chenx/DomiRank/domirank.py", line 262, in optimal_sigma
    minEig = np.where(finalErrors == finalErrors.min())[0][-1]
  File "/home/chenx/anaconda3/envs/domirank/lib/python3.10/site-packages/numpy/core/_methods.py", line 45, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
TypeError: '<=' not supported between instances of 'NoneType' and 'NoneType'
```

**Comment by mengsig** [comment]
Hello @chenshuai17 ,

Yes, I see the error in the repository. I have fixed it now. Please git pull once again and try. It should work now.

Thank you for raising this concern!

Best,
Marcus
